import pandas as pd
from datetime import datetime
from pathlib import Path
import logging

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger(__name__)

def generate_mock_data(data_dir: Path) -> None:
    """Generates sample CSVs representing a typical enterprise IT environment."""
    data_dir.mkdir(parents=True, exist_ok=True)
    
    hr_data = {
        'Employee_ID': ['EMP001', 'EMP002', 'EMP003', 'EMP005', 'EMP006'],
        'Name': ['Alice Smith', 'Bob Jones', 'Charlie Brown', 'Eve Davis', 'Frank White'],
        'Department': ['Procurement', 'Stores', 'Transport', 'Management', 'IT'],
        'Status': ['Active', 'Active', 'Active', 'Active', 'Active']
    }
    pd.DataFrame(hr_data).to_csv(data_dir / 'hr_roster.csv', index=False)

    it_data = {
        'Account_ID': ['EMP001', 'EMP002', 'EMP003', 'EMP004', 'EMP007'],
        'Username': ['asmith', 'bjones', 'cbrown', 'ddaniels', 'gclark'],
        'Last_Login': ['2026-09-29', '2026-09-28', '2026-09-30', '2026-08-15', '2026-09-01'],
        'Access_Level': ['Standard', 'Standard', 'Standard', 'Admin', 'Standard']
    }
    pd.DataFrame(it_data).to_csv(data_dir / 'it_active_users.csv', index=False)
    logger.info(f"Mock datasets successfully generated in ./{data_dir.name}/")

def run_security_audit(data_dir: Path) -> pd.DataFrame:
    """Compares IT active users against the active HR roster to find ghost accounts."""
    logger.info("Initiating automated access audit...")
    
    hr_path = data_dir / 'hr_roster.csv'
    it_path = data_dir / 'it_active_users.csv'

    if not hr_path.exists() or not it_path.exists():
        raise FileNotFoundError("Missing required CSV files in data directory.")

    hr_df = pd.read_csv(hr_path)
    it_df = pd.read_csv(it_path)

    merged = it_df.merge(hr_df, left_on='Account_ID', right_on='Employee_ID', how='left')
    ghost_accounts = merged[merged['Employee_ID'].isna()]
    
    logger.info(f"Audit complete. Detected {len(ghost_accounts)} unauthorized 'ghost' accounts.")
    return ghost_accounts

def generate_audit_report(ghost_accounts: pd.DataFrame, report_dir: Path) -> None:
    """Outputs the findings into a clean, actionable Markdown report."""
    report_dir.mkdir(parents=True, exist_ok=True)
    report_date = datetime.now().strftime("%Y-%m-%d")
    filename = report_dir / f"Security_Audit_{report_date}.md"
    
    with open(filename, "w") as f:
        f.write(f"# 🛡️ Automated Access Security Audit\n")
        f.write(f"**Date:** {report_date}\n")
        f.write(f"**Generated By:** SecAuto Script v1.0\n\n")
        
        if ghost_accounts.empty:
            f.write("✅ **Status: Secure.** All active IT accounts match active HR employees.\n")
        else:
            f.write("## 🚨 Security Alert: Ghost Accounts Detected\n")
            f.write("The following accounts have active system access but are not found in the current HR active employee roster. **Immediate revocation recommended.**\n\n")
            
            f.write("| Account ID | Username | Last Login | Access Level |\n")
            f.write("|---|---|---|---|\n")
            for _, row in ghost_accounts.iterrows():
                access = f"**{row['Access_Level']}**" if row['Access_Level'] == 'Admin' else row['Access_Level']
                f.write(f"| {row['Account_ID']} | {row['Username']} | {row['Last_Login']} | {access} |\n")
    
    logger.info(f"Audit report successfully exported to: {filename}")

if __name__ == "__main__":
    BASE_DIR = Path(__file__).resolve().parent
    DATA_DIR = BASE_DIR / "data"
    REPORT_DIR = BASE_DIR / "reports"

    logger.info("Starting Security Audit Pipeline...")
    generate_mock_data(DATA_DIR)
    anomalies = run_security_audit(DATA_DIR)
    generate_audit_report(anomalies, REPORT_DIR)
    logger.info("Pipeline execution finished successfully.")
